import inspect
from functools import wraps
from typing import (
    TYPE_CHECKING,
    Any,
    Callable,
    Coroutine,
    Iterable,
    ParamSpec,
    TypeVar,
    overload,
)

from beartype import beartype
from sqlalchemy import (
    Boolean,
    ColumnExpressionArgument,
    Integer,
    ScalarResult,
    String,
    UniqueConstraint,
    UpdateBase,
    create_engine,
    sql,
)
from sqlalchemy.dialects import mysql, postgresql, sqlite
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, sessionmaker
from sqlalchemy.orm import Session as SQLSession

from common import settings
from validations import logger

if TYPE_CHECKING:
    from typing import cast


T = TypeVar("T", bound=Any)
P = ParamSpec("P")


class DBBase(DeclarativeBase):
    """
    This class serves as a base for all tables used by the bot. It should not be referenced directly, as its only purpose is running the create_all() command at the end of this file.
    """

    pass


class DBBridge(DBBase):
    """
    An SQLAlchemy ORM class representing a database table tracking existing bridges between channels and/or threads.

    Columns
    -------
    - `id (INT)`: The id number of a bridge, has `PRIMARY KEY` and `AUTO_INCREMENT`.
    - `source (VARCHAR(32))`: The ID of the bridge's source channel or thread.
    - `target (VARCHAR(32))`: The ID of the bridge's target channel or thread.

    Constraints
    -----------
    - `unique_source_target (UNIQUE(source, target))`: A combination of source and target channel or thread IDs has to be unique.
    """

    __tablename__ = "bridges"
    __table_args__ = (
        UniqueConstraint("source", "target", name="unique_source_target"),
    )

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    source: Mapped[str] = mapped_column(String(32), nullable=False)
    target: Mapped[str] = mapped_column(String(32), nullable=False)


class DBWebhook(DBBase):
    """
    An SQLAlchemy ORM class representing a database table tracking webhooks managed by the bot in each channel.

    Columns
    -------
    - `channel (VARCHAR(32))`: The ID of the bridge's target channel or thread. Has `PRIMARY KEY`.
    - `webhook (VARCHAR(32))`: The ID of the webhook attached to the target channel which bridges messages to it.
    """

    __tablename__ = "webhooks"

    channel: Mapped[str] = mapped_column(String(32), primary_key=True)
    webhook: Mapped[str] = mapped_column(String(32))


class DBMessageMap(DBBase):
    """
    An SQLAlchemy ORM class representing a database table listing the mappings between bridged messages.

    Columns
    -------
    - `id (INT)`: The id number of a mapping, has `PRIMARY KEY` and `AUTO_INCREMENT`.
    - `source_message (VARCHAR(32))`: The ID of the message in the original channel.
    - `source_channel (VARCHAR(32))`: The ID of the channel or thread that message was sent to.
    - `target_message (VARCHAR(32))`: The ID of the message generated by the bot across a bridge.
    - `forward_header_message (VARCHAR(32))`: The ID of a message that's the header for a bridged forwarded message.
    - `target_channel (VARCHAR(32))`: The ID of the channel or thread the bridged message was bridged to.
    - `target_message_order (INT)`: If the bridged message had to be sent as multiple messages due to being too long, this stores which message in the order this one is.
    - `webhook (VARCHAR(32))`: The ID of the webhook that posted the message.
    """

    __tablename__ = "message_mappings"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    source_message: Mapped[str] = mapped_column(String(32), nullable=False)
    source_channel: Mapped[str] = mapped_column(String(32), nullable=False)
    target_message: Mapped[str] = mapped_column(String(32), nullable=False)
    forward_header_message: Mapped[str] = mapped_column(String(32), nullable=True)
    target_channel: Mapped[str] = mapped_column(String(32), nullable=False)
    target_message_order: Mapped[int] = mapped_column(Integer(), nullable=True)
    webhook: Mapped[str] = mapped_column(String(32), nullable=True)


class DBReactionMap(DBBase):
    """
    An SQLAlchemy ORM class representing a database table listing the mappings between bridged reactions.

    Columns
    -------
    - `id (INT)`: The id number of a mapping, has `PRIMARY KEY` and `AUTO_INCREMENT`.
    - `source_emoji (VARCHAR(30))`: The ID of the emoji in the source message.
    - `source_message (VARCHAR(32))`: The ID of the message in the original channel.
    - `source_channel (VARCHAR(32))`: The ID of the channel or thread that message was sent to.
    - `target_message (VARCHAR(32))`: The ID of the message that got this reaction bridged to it.
    - `target_channel (VARCHAR(32))`: The ID of the channel or thread that message is in.
    - `target_emoji_id (VARCHAR(32))`: The ID of the emoji in the target message.
    - `target_emoji_name (VARCHAR(32))`: The name of the emoji in the target message.

    Constraints
    -----------
    - `unique_emoji_source_target (UNIQUE(source_emoji, source_message, target_message))`: A combination of source emoji, source message, and target message has to be unique.
    """

    __tablename__ = "reaction_mappings"
    __table_args__ = (
        UniqueConstraint(
            "source_emoji",
            "source_message",
            "target_message",
            name="unique_emoji_source_target",
        ),
    )

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    source_emoji: Mapped[str] = mapped_column(String(32), nullable=False)
    source_message: Mapped[str] = mapped_column(String(32), nullable=False)
    source_channel: Mapped[str] = mapped_column(String(32), nullable=False)
    target_message: Mapped[str] = mapped_column(String(32), nullable=False)
    target_channel: Mapped[str] = mapped_column(String(32), nullable=False)
    target_emoji_id: Mapped[str] = mapped_column(String(32), nullable=True)
    target_emoji_name: Mapped[str] = mapped_column(String(32), nullable=True)


class DBAutoBridgeThreadChannels(DBBase):
    """
    An SQLAlchemy ORM class representing a database table listing all channels that will automatically bridge newly-created threads.

    Columns
    -------
    - `id (INT)`: The id number of an entry, has `PRIMARY KEY` and `AUTO_INCREMENT`.
    - `channel (VARCHAR(32))`: The ID of the channel that has auto-bridge-threads enabled.
    """

    __tablename__ = "auto_bridge_thread_channels"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    channel: Mapped[str] = mapped_column(String(32), nullable=False)


class DBEmoji(DBBase):
    """
    An SQLAlchemy ORM class representing a database table storing information about emoji.

    Columns
    -------
    - `id (VARCHAR(32))`: The emoji ID, has `PRIMARY KEY`.
    - `name (VARCHAR(32))`: The name of the emoji.
    - `server_id (VARCHAR(32))`: The ID of the server this emoji belongs to.
    - `animated (BOOL)`: Whether it's an animated emoji.
    - `image_hash (VARCHAR(32))`: A hash of this emoji's image.
    - `accessible (BOOL)`: Whether the bot has access to this emoji.
    """

    __tablename__ = "emoji"

    id: Mapped[str] = mapped_column(String(32), primary_key=True)
    name: Mapped[str] = mapped_column(String(32), nullable=True)
    server_id: Mapped[str] = mapped_column(String(32), nullable=True)
    animated: Mapped[bool] = mapped_column(Boolean, nullable=True)
    image_hash: Mapped[str] = mapped_column(String(32), nullable=True)
    accessible: Mapped[bool] = mapped_column(Boolean, nullable=False)


class DBAppWhitelist(DBBase):
    """
    An SQLAlchemy ORM class representing a database table storing IDs for applications/bots that are whitelisted for bridging messages in a given channel.

    Columns
    -------
    - `id (INT)`: The id number of an entry, has `PRIMARY KEY` and `AUTO_INCREMENT`.
    - `channel (VARCHAR(32))`: The ID of a source channel.
    - `application (VARCHAR(32))`: The ID of the application whose messages should be allowed through from that channel.

    Constraints
    -----------
    - `unique_channel_app (UNIQUE(channel, application))`: A combination of channel and application IDs has to be unique.
    """

    __tablename__ = "app_whitelist"
    __table_args__ = (
        UniqueConstraint("channel", "application", name="unique_channel_app"),
    )

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    channel: Mapped[str] = mapped_column(String(32), nullable=False)
    application: Mapped[str] = mapped_column(String(32), nullable=False)


Table = (
    DBBridge
    | DBWebhook
    | DBMessageMap
    | DBReactionMap
    | DBReactionMap
    | DBAutoBridgeThreadChannels
    | DBEmoji
    | DBAppWhitelist
)
TableType = TypeVar("TableType", bound=Table)


def sql_select(
    from_: type[TableType],
    *,
    where: ColumnExpressionArgument[bool] | None = None,
    order_by: ColumnExpressionArgument[Any] | str | None = None,
    session: SQLSession,
) -> ScalarResult[TableType]:
    """Return an iterator with the results of a "select" expression on a table, optionally with some conditions.

    Parameters
    ----------
    from_ : type[:class:`~database.DBBridge`] | type[:class:`~database.DBWebhook`] | type[:class:`~database.DBMessageMap`] | type[:class:`~database.DBReactionMap`] | type[:class:`~database.DBAutoBridgeThreadChannels`] | type[:class:`~database.DBEmoji`]
        The table to select from.
    where : :class:`~sqlalchemyColumnExpressionArgument`[bool] | None, optional
        Any conditions to use to select from the table. Defaults to None, in which case no filtering will be done.
    order_by : :class:`~sqlalchemyColumnExpressionArgument`[Any] | str | None, optional
        Any column to be used to order the results by. Defaults to None, in which case no ordering will be done.
    session : :class:`~sqlalchemy.orm.SQLSession`
        An SQLAlchemy ORM Session connecting to the database.

    Returns
    -------
    :class:`~sqlalchemy.ScalarResult`[:class:`~database.DBBridge` | :class:`~database.DBWebhook` | :class:`~database.DBMessageMap` | :class:`~database.DBReactionMap` | :class:`~database.DBAutoBridgeThreadChannels` | :class:`~database.DBEmoji`]
    """
    select = sql.select(from_)
    if where is not None:
        select = select.where(where)
    if order_by is not None:
        select = select.order_by(order_by)

    return session.scalars(select)


@beartype
def get_sql_upsert_query(
    table: type[Table],
    *,
    indices: Iterable[str],
    ignored_cols: Iterable[str] | None = None,
    **kwargs: Any,
) -> UpdateBase:
    """Return an :class:`~sqlalchemy.UpdateBase` for inserting values into a table if a set of indices is not duplicated or updating them if it is.

    Parameters
    ----------
    table : type[:class:`~database.DBBridge`] | type[:class:`~database.DBWebhook`] | type[:class:`~database.DBMessageMap`] | type[:class:`~database.DBReactionMap`] | type[:class:`~database.DBAutoBridgeThreadChannels`] | type[:class:`~database.DBEmoji`]
        The table to insert into.
    indices : Iterable[str]
        A list with the names of the indices (i.e. the columns whose uniqueness will be checked).
    ignored_cols : Iterable[str] | None, optional
        A list with the names of columns whose values should not be updated but which aren't, themselves, unique indices. Defaults to None.
    **kwargs : Any
        Named arguments for the values to insert or update. The values in `indices` must be a [proper subset](https://en.wikipedia.org/wiki/Subset) of the keys in `kwargs` (i.e. all `indices` should be in `kwargs.keys()` but there should be at least one key in `kwargs` that isn't in `indices`).

    Returns
    -------
    :class:`~sqlalchemy.UpdateBase`

    Raises
    ------
    ValueError
        `indices` is not a proper subset of `kwargs.keys()`.
    :class:`~sqlalchemy.exc.StatementError`
        SQL statement inferred from arguments was invalid or database connection failed. This error can only be raised if the database dialect is not MySQL, PostgreSQL, nor SQLite.
    """
    indices = set(indices)
    insert_values = kwargs
    insert_value_keys = set(insert_values.keys())
    if not indices < insert_value_keys:
        raise ValueError("keys is not a proper subset of kwargs.keys().")

    if ignored_cols:
        ignored_cols = set(ignored_cols)
    else:
        ignored_cols = {}
    update_values = {
        key: value
        for key, value in insert_values.items()
        if key not in indices.union(ignored_cols)
    }

    db_dialect = engine.dialect.name
    if db_dialect == "mysql":
        return (
            mysql.insert(table)
            .values(**insert_values)
            .on_duplicate_key_update(**update_values)
        )
    elif db_dialect in {"postgresql", "sqlite"}:
        insert: postgresql.Insert | sqlite.Insert
        if db_dialect == "postgresql":
            insert = postgresql.insert(table)
        else:
            insert = sqlite.insert(table)

        return insert.values(**insert_values).on_conflict_do_update(
            index_elements=indices,
            set_=update_values,
        )
    else:
        # I'll do a manual update in this case
        with Session() as session:
            index_values = [
                getattr(table, idx) == insert_values[idx] for idx in indices
            ]
            upsert: UpdateBase

            def select_existing(session: SQLSession):
                return session.execute(sql.select(table).where(*index_values)).first()

            if select_existing(session):
                # Values with those keys do exist, so I update
                upsert = sql.Update(table).where(*index_values).values(**update_values)
            else:
                upsert = sql.insert(table).values(**insert_values)

        return upsert


@beartype
def get_sql_insert_ignore_duplicate_query(
    table: type[Table],
    *,
    indices: Iterable[str],
    **kwargs: Any,
) -> UpdateBase:
    """Return an :class:`~sqlalchemy.UpdateBase` for inserting values into a table if a set of indices is not duplicated.

    Parameters
    ----------
    table : type[:class:`~database.DBBridge`] | type[:class:`~database.DBWebhook`] | type[:class:`~database.DBMessageMap`] | type[:class:`~database.DBReactionMap`] | type[:class:`~database.DBAutoBridgeThreadChannels`] | type[:class:`~database.DBEmoji`]
        The table to insert into.
    indices : Iterable[str]
        A list with the names of the indices (i.e. the columns whose uniqueness will be checked).
    **kwargs : Any
        Named arguments for the values to insert or update. The values in `indices` must be a [proper subset](https://en.wikipedia.org/wiki/Subset) of the keys in `kwargs` (i.e. all `indices` should be in `kwargs.keys()` but there should be at least one key in `kwargs` that isn't in `indices`).

    Returns
    -------
    :class:`~sqlalchemy.UpdateBase`

    Raises
    ------
    :class:`~sqlalchemy.exc.StatementError`
        SQL statement inferred from arguments was invalid or database connection failed. This error can only be raised if the database dialect is not MySQL, PostgreSQL, nor SQLite.
    """
    indices = set(indices)
    insert_values = kwargs

    db_dialect = engine.dialect.name
    if db_dialect == "mysql":
        random_index = indices.pop()
        return (
            mysql.insert(table)
            .values(**insert_values)
            .on_duplicate_key_update(**{random_index: getattr(table, random_index)})
        )
    elif db_dialect in {"postgresql", "sqlite"}:
        insert: postgresql.Insert | sqlite.Insert
        if db_dialect == "postgresql":
            insert = postgresql.insert(table)
        else:
            insert = sqlite.insert(table)

        return insert.values(**insert_values).on_conflict_do_nothing()
    else:
        # I'll do a manual update in this case
        with Session() as session:
            index_values = [
                getattr(table, idx) == insert_values[idx] for idx in indices
            ]
            insert_unknown: UpdateBase

            def select_existing(session: SQLSession):
                return session.execute(sql.select(table).where(*index_values)).first()

            if select_existing(session):
                # Values with those keys do exist, so I do nothing
                random_index = indices.pop()
                insert_unknown = sql.Update(table).values(
                    **{random_index: getattr(table, random_index)}
                )
            else:
                insert_unknown = sql.insert(table).values(**insert_values)

        return insert_unknown


@overload
def sql_command(
    commit_results: Callable[P, Coroutine[Any, Any, T]],
) -> Callable[P, Coroutine[Any, Any, T]]:
    """Decorator that checks whether the :class:`~sqlalchemy.orm.Session`-typed argument of a function exists and is valid, and runs the function with it if so. Otherwise, it create a Python context manager with the session and calls the function within it.

    Using the decorator with no arguments will commit the results of running the function to the database and will assume that the name of the argument to the function that should contain the session is "session".
    """
    ...


@overload
def sql_command(commit_results: Callable[P, T]) -> Callable[P, T]:
    """Decorator that checks whether the :class:`~sqlalchemy.orm.Session`-typed argument of a function exists and is valid, and runs the function with it if so. Otherwise, it create a Python context manager with the session and calls the function within it.

    Using the decorator with no arguments will commit the results of running the function to the database and will assume that the name of the argument to the function that should contain the session is "session".
    """
    pass


@overload
def sql_command(
    commit_results: bool = True,
    session_keyword: str = "session",
) -> (
    Callable[[Callable[P, Coroutine[Any, Any, T]]], Callable[P, Coroutine[Any, Any, T]]]
    | Callable[[Callable[P, T]], Callable[P, T]]
):
    """Decorator that checks whether the :class:`~sqlalchemy.orm.Session`-typed argument of a function exists and is valid, and runs the function with it if so. Otherwise, it create a Python context manager with the session and calls the function within it.

    Parameters
    ----------
    commit_results : bool, optional
        Whether to commit the results of the session to the database, or roll them back in case of an error. Defaults to True.
    session_keyword : str, optional
        The name of the argument that is meant to store the session in the function. Defaults to "session".
    """
    ...


def sql_command(
    commit_results: Callable[P, T] | Callable[P, Coroutine[Any, Any, T]] | bool = True,
    session_keyword: str = "session",
) -> (
    Callable[[Callable[P, T]], Callable[P, T]]
    | Callable[
        [Callable[P, Coroutine[Any, Any, T]]],
        Callable[P, Coroutine[Any, Any, T]],
    ]
    | Callable[P, Coroutine[Any, Any, T]]
    | Callable[P, T]
):
    if callable(commit_results):
        calling_function = commit_results
        commit_results = True
    else:
        calling_function = None

    @overload
    def decorator(func: Callable[P, T]) -> Callable[P, T]: ...

    @overload
    def decorator(
        func: Callable[P, Coroutine[Any, Any, T]],
    ) -> Callable[P, Coroutine[Any, Any, T]]: ...

    def decorator(
        func: Callable[P, T] | Callable[P, Coroutine[Any, Any, T]],
    ) -> Callable[P, T] | Callable[P, Coroutine[Any, Any, T]]:
        if inspect.iscoroutinefunction(func):
            if TYPE_CHECKING:
                func = cast(Callable[P, Coroutine[Any, Any, T]], func)

            @wraps(func)
            async def wrapper_func_async(*args, **kwargs) -> T:
                if isinstance(kwargs.get(session_keyword), SQLSession):
                    return await func(*args, **kwargs)

                with Session() as session:
                    kwargs[session_keyword] = session
                    if commit_results:
                        with session.begin():
                            return await func(*args, **kwargs)
                    return await func(*args, **kwargs)

            wrapper_func = wrapper_func_async
        else:
            if TYPE_CHECKING:
                func = cast(Callable[P, T], func)

            @wraps(func)
            def wrapper_func_sync(*args, **kwargs) -> T:
                if isinstance(kwargs.get(session_keyword), SQLSession):
                    return func(*args, **kwargs)

                with Session() as session:
                    kwargs[session_keyword] = session
                    if commit_results:
                        with session.begin():
                            return func(*args, **kwargs)
                    return func(*args, **kwargs)

            wrapper_func = wrapper_func_sync

        return wrapper_func

    if calling_function is not None:
        return decorator(calling_function)
    else:
        return decorator


# Create the engine connecting to the database
logger.info("Creating engine to connect to database...")
engine = create_engine(
    f"{settings['db_dialect']}+{settings['db_driver']}://{settings['db_user']}:{settings['db_pwd']}@{settings['db_host']}:{settings['db_port']}/{settings['db_name']}",
    pool_pre_ping=True,
    pool_recycle=3600,
)
Session = sessionmaker(engine)
logger.info("Created.")

# Create all tables represented by the above classes, if they haven't already been created
logger.info("Ensuring all necessary tables exist...")
try:
    DBBase.metadata.create_all(engine)
except Exception as e:
    logger.error("An error occurred while trying to create necessary tables: %s", e)
    raise
logger.info("All necessary tables are available.")
