from datetime import datetime, timezone
from functools import wraps
from typing import (
    TYPE_CHECKING,
    Any,
    Callable,
    Coroutine,
    Iterable,
    ParamSpec,
    TypeVar,
    overload,
)

from sparkqlalchemy import AsyncDataFrame, Row, functions  # noqa: F401
from sqlalchemy import (
    Boolean,
    Column,
    Connection,
    DateTime,
    Dialect,
    Integer,
    String,
    UniqueConstraint,
    UpdateBase,
    func,
    inspect,
    sql,
    text,
)
from sqlalchemy.dialects import mysql, postgresql, sqlite
from sqlalchemy.ext.asyncio import AsyncEngine, async_sessionmaker, create_async_engine
from sqlalchemy.ext.asyncio import AsyncSession as SQLSession
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from common import settings
from validations import logger

if TYPE_CHECKING:
    from sqlalchemy.sql.functions import GenericFunction

T = TypeVar("T", bound=Any)
P = ParamSpec("P")


class DBBase(DeclarativeBase):
    """
    This class serves as a base for all tables used by the bot. It should not be referenced directly, as its only purpose is running the create_all() command at the end of this file.
    """

    pass


class DBBridge(DBBase):
    """
    An SQLAlchemy ORM class representing a database table tracking existing bridges between channels and/or threads.

    Columns
    -------
    - `id (INT)`: The id number of a bridge, has `PRIMARY KEY` and `AUTO_INCREMENT`.
    - `created_at (TIMESTAMP)`: When the bridge was created.
    - `source (VARCHAR(32))`: The ID of the bridge's source channel or thread.
    - `target (VARCHAR(32))`: The ID of the bridge's target channel or thread.

    Constraints
    -----------
    - `unique_source_target (UNIQUE(source, target))`: A combination of source and target channel or thread IDs has to be unique.
    """

    __tablename__ = "bridges"
    __table_args__ = (
        UniqueConstraint("source", "target", name="unique_source_target"),
    )

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    source: Mapped[str] = mapped_column(String(32), nullable=False)
    target: Mapped[str] = mapped_column(String(32), nullable=False)


class DBWebhook(DBBase):
    """
    An SQLAlchemy ORM class representing a database table tracking webhooks managed by the bot in each channel.

    Columns
    -------
    - `channel (VARCHAR(32))`: The ID of the bridge's target channel or thread. Has `PRIMARY KEY`.
    - `webhook (VARCHAR(32))`: The ID of the webhook attached to the target channel which bridges messages to it.
    - `created_at (TIMESTAMP)`: When the webhook was created.
    """

    __tablename__ = "webhooks"

    channel: Mapped[str] = mapped_column(String(32), primary_key=True)
    webhook: Mapped[str] = mapped_column(String(32))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )


class DBMessageMap(DBBase):
    """
    An SQLAlchemy ORM class representing a database table listing the mappings between bridged messages.

    Columns
    -------
    - `id (INT)`: The id number of a mapping, has `PRIMARY KEY` and `AUTO_INCREMENT`.
    - `sent_at (TIMESTAMP)`: When the message was sent.
    - `source_message (VARCHAR(32))`: The ID of the message in the original channel.
    - `source_channel (VARCHAR(32))`: The ID of the channel or thread that message was sent to.
    - `target_message (VARCHAR(32))`: The ID of the message generated by the bot across a bridge.
    - `forward_header_message (VARCHAR(32))`: The ID of a message that's the header for a bridged forwarded message.
    - `extra_attachments_footer_message (VARCHAR(32))`: The ID of a message that's the footer for a message that had attachments too large to be copied to the bridged message.
    - `target_channel (VARCHAR(32))`: The ID of the channel or thread the bridged message was bridged to.
    - `target_message_order (INT)`: If the bridged message had to be sent as multiple messages due to being too long, this stores which message in the order this one is.
    - `webhook (VARCHAR(32))`: The ID of the webhook that posted the message.
    """

    __tablename__ = "message_mappings"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    sent_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    source_message: Mapped[str] = mapped_column(String(32), nullable=False)
    source_channel: Mapped[str] = mapped_column(String(32), nullable=False)
    target_message: Mapped[str] = mapped_column(String(32), nullable=False)
    forward_header_message: Mapped[str] = mapped_column(String(32), nullable=True)
    extra_attachments_footer_message: Mapped[str] = mapped_column(
        String(32),
        nullable=True,
    )
    target_channel: Mapped[str] = mapped_column(String(32), nullable=False)
    target_message_order: Mapped[int] = mapped_column(Integer(), nullable=True)
    webhook: Mapped[str] = mapped_column(String(32), nullable=True)


class DBMostRecentEventInChannel(DBBase):
    """
    An SQLAlchemy ORM class representing a database table with the most recent event observed in a bridged channel.

    Columns
    -------
    - `id (INT)`: The id number of a channel's most recent event, has `PRIMARY KEY` and `AUTO_INCREMENT`.
    - `channel (VARCHAR(32))`: The ID of the channel or thread the event was observed in.
    - `message (VARCHAR(32))`: The ID of the most recently sent message.
    - `observed_at (TIMESTAMP)`: When the event was observed.
    """

    __tablename__ = "most_recent_event_in_channel"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    channel: Mapped[str] = mapped_column(String(32), nullable=False, unique=True)
    message: Mapped[str] = mapped_column(String(32), nullable=True)
    observed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )


class DBReactionMap(DBBase):
    """
    An SQLAlchemy ORM class representing a database table listing the mappings between bridged reactions.

    Columns
    -------
    - `id (INT)`: The id number of a mapping, has `PRIMARY KEY` and `AUTO_INCREMENT`.
    - `added_at (TIMESTAMP)`: When the reaction was added.
    - `source_emoji (VARCHAR(30))`: The ID of the emoji in the source message.
    - `source_message (VARCHAR(32))`: The ID of the message in the original channel.
    - `source_channel (VARCHAR(32))`: The ID of the channel or thread that message was sent to.
    - `target_message (VARCHAR(32))`: The ID of the message that got this reaction bridged to it.
    - `target_channel (VARCHAR(32))`: The ID of the channel or thread that message is in.
    - `target_emoji_id (VARCHAR(32))`: The ID of the emoji in the target message.
    - `target_emoji_name (VARCHAR(32))`: The name of the emoji in the target message.

    Constraints
    -----------
    - `unique_emoji_source_target (UNIQUE(source_emoji, source_message, target_message))`: A combination of source emoji, source message, and target message has to be unique.
    """

    __tablename__ = "reaction_mappings"
    __table_args__ = (
        UniqueConstraint(
            "source_emoji",
            "source_message",
            "target_message",
            name="unique_emoji_source_target",
        ),
    )

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    added_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    source_emoji: Mapped[str] = mapped_column(String(32), nullable=False)
    source_message: Mapped[str] = mapped_column(String(32), nullable=False)
    source_channel: Mapped[str] = mapped_column(String(32), nullable=False)
    target_message: Mapped[str] = mapped_column(String(32), nullable=False)
    target_channel: Mapped[str] = mapped_column(String(32), nullable=False)
    target_emoji_id: Mapped[str] = mapped_column(String(32), nullable=True)
    target_emoji_name: Mapped[str] = mapped_column(String(32), nullable=True)


class DBAutoBridgeThreadChannels(DBBase):
    """
    An SQLAlchemy ORM class representing a database table listing all channels that will automatically bridge newly-created threads.

    Columns
    -------
    - `id (INT)`: The id number of an entry, has `PRIMARY KEY` and `AUTO_INCREMENT`.
    - `channel (VARCHAR(32))`: The ID of the channel that has auto-bridge-threads enabled.
    """

    __tablename__ = "auto_bridge_thread_channels"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    channel: Mapped[str] = mapped_column(String(32), nullable=False)


class DBEmoji(DBBase):
    """
    An SQLAlchemy ORM class representing a database table storing information about emoji.

    Columns
    -------
    - `id (VARCHAR(32))`: The emoji ID, has `PRIMARY KEY`.
    - `name (VARCHAR(32))`: The name of the emoji.
    - `server_id (VARCHAR(32))`: The ID of the server this emoji belongs to.
    - `animated (BOOL)`: Whether it's an animated emoji.
    - `image_hash (VARCHAR(32))`: A hash of this emoji's image.
    - `accessible (BOOL)`: Whether the bot has access to this emoji.
    """

    __tablename__ = "emoji"

    id: Mapped[str] = mapped_column(String(32), primary_key=True)
    name: Mapped[str] = mapped_column(String(32), nullable=True)
    server_id: Mapped[str] = mapped_column(String(32), nullable=True)
    animated: Mapped[bool] = mapped_column(Boolean, nullable=True)
    image_hash: Mapped[str] = mapped_column(String(32), nullable=True)
    accessible: Mapped[bool] = mapped_column(Boolean, nullable=False)


class DBAppWhitelist(DBBase):
    """
    An SQLAlchemy ORM class representing a database table storing IDs for applications/bots that are whitelisted for bridging messages in a given channel.

    Columns
    -------
    - `id (INT)`: The id number of an entry, has `PRIMARY KEY` and `AUTO_INCREMENT`.
    - `channel (VARCHAR(32))`: The ID of a source channel.
    - `application (VARCHAR(32))`: The ID of the application whose messages should be allowed through from that channel.

    Constraints
    -----------
    - `unique_channel_app (UNIQUE(channel, application))`: A combination of channel and application IDs has to be unique.
    """

    __tablename__ = "app_whitelist"
    __table_args__ = (
        UniqueConstraint("channel", "application", name="unique_channel_app"),
    )

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    channel: Mapped[str] = mapped_column(String(32), nullable=False)
    application: Mapped[str] = mapped_column(String(32), nullable=False)


Table = (
    DBBridge
    | DBWebhook
    | DBMessageMap
    | DBMostRecentEventInChannel
    | DBReactionMap
    | DBAutoBridgeThreadChannels
    | DBEmoji
    | DBAppWhitelist
)


async def get_sql_upsert_query(
    table: type[Table],
    *,
    indices: Iterable[str],
    ignored_cols: Iterable[str] | None = None,
    **kwargs: Any,
) -> UpdateBase:
    """Return an :class:`~sqlalchemy.UpdateBase` for inserting values into a table if a set of indices is not duplicated or updating them if it is.

    Parameters
    ----------
    table : type[:class:`~database.DBBridge`] | type[:class:`~database.DBWebhook`] | type[:class:`~database.DBMessageMap`] | type[:class:`~database.DBReactionMap`] | type[:class:`~database.DBAutoBridgeThreadChannels`] | type[:class:`~database.DBEmoji`]
        The table to insert into.
    indices : Iterable[str]
        A list with the names of the indices (i.e. the columns whose uniqueness will be checked).
    ignored_cols : Iterable[str] | None, optional
        A list with the names of columns whose values should not be updated but which aren't, themselves, unique indices. Defaults to None.
    **kwargs : Any
        Named arguments for the values to insert or update. The values in `indices` must be a [proper subset](https://en.wikipedia.org/wiki/Subset) of the keys in `kwargs` (i.e. all `indices` should be in `kwargs.keys()` but there should be at least one key in `kwargs` that isn't in `indices`).

    Returns
    -------
    :class:`~sqlalchemy.UpdateBase`

    Raises
    ------
    ValueError
        `indices` is not a proper subset of `kwargs.keys()`.
    :class:`~sqlalchemy.exc.StatementError`
        SQL statement inferred from arguments was invalid or database connection failed. This error can only be raised if the database dialect is not MySQL, PostgreSQL, nor SQLite.
    """
    indices = set(indices)
    insert_values = kwargs
    insert_value_keys = set(insert_values.keys())
    if not indices < insert_value_keys:
        raise ValueError("keys is not a proper subset of kwargs.keys().")

    if ignored_cols:
        ignored_cols = set(ignored_cols)
    else:
        ignored_cols = {}
    update_values = {
        key: value
        for key, value in insert_values.items()
        if key not in indices.union(ignored_cols)
    }

    db_dialect = engine.dialect.name
    if db_dialect == "mysql":
        return (
            mysql.insert(table)
            .values(**insert_values)
            .on_duplicate_key_update(**update_values)
        )
    elif db_dialect in {"postgresql", "sqlite"}:
        insert: postgresql.Insert | sqlite.Insert
        if db_dialect == "postgresql":
            insert = postgresql.insert(table)
        else:
            insert = sqlite.insert(table)

        return insert.values(**insert_values).on_conflict_do_update(
            index_elements=indices,
            set_=update_values,
        )
    else:
        # I'll do a manual update in this case
        async with Session() as session:
            index_values = [
                getattr(table, idx) == insert_values[idx] for idx in indices
            ]
            upsert: UpdateBase

            existing = (
                await session.execute(sql.select(table).where(*index_values))
            ).first()

            if existing:
                # Values with those keys do exist, so I update
                upsert = sql.Update(table).where(*index_values).values(**update_values)
            else:
                upsert = sql.insert(table).values(**insert_values)

        return upsert


async def get_sql_insert_ignore_duplicate_query(
    table: type[Table],
    *,
    indices: Iterable[str],
    **kwargs: Any,
) -> UpdateBase:
    """Return an :class:`~sqlalchemy.UpdateBase` for inserting values into a table if a set of indices is not duplicated.

    Parameters
    ----------
    table : type[:class:`~database.DBBridge`] | type[:class:`~database.DBWebhook`] | type[:class:`~database.DBMessageMap`] | type[:class:`~database.DBReactionMap`] | type[:class:`~database.DBAutoBridgeThreadChannels`] | type[:class:`~database.DBEmoji`]
        The table to insert into.
    indices : Iterable[str]
        A list with the names of the indices (i.e. the columns whose uniqueness will be checked).
    **kwargs : Any
        Named arguments for the values to insert or update. The values in `indices` must be a [proper subset](https://en.wikipedia.org/wiki/Subset) of the keys in `kwargs` (i.e. all `indices` should be in `kwargs.keys()` but there should be at least one key in `kwargs` that isn't in `indices`).

    Returns
    -------
    :class:`~sqlalchemy.UpdateBase`

    Raises
    ------
    :class:`~sqlalchemy.exc.StatementError`
        SQL statement inferred from arguments was invalid or database connection failed. This error can only be raised if the database dialect is not MySQL, PostgreSQL, nor SQLite.
    """
    indices = set(indices)
    insert_values = kwargs

    db_dialect = engine.dialect.name
    if db_dialect == "mysql":
        random_index = indices.pop()
        return (
            mysql.insert(table)
            .values(**insert_values)
            .on_duplicate_key_update(**{random_index: getattr(table, random_index)})
        )
    elif db_dialect in {"postgresql", "sqlite"}:
        insert: postgresql.Insert | sqlite.Insert
        if db_dialect == "postgresql":
            insert = postgresql.insert(table)
        else:
            insert = sqlite.insert(table)

        return insert.values(**insert_values).on_conflict_do_nothing()
    else:
        # I'll do a manual update in this case
        async with Session() as session:
            index_values = [
                getattr(table, idx) == insert_values[idx] for idx in indices
            ]
            insert_unknown: UpdateBase

            existing = (
                await session.execute(sql.select(table).where(*index_values))
            ).first()

            if existing:
                # Values with those keys do exist, so I do nothing
                random_index = indices.pop()
                insert_unknown = sql.Update(table).values(
                    **{random_index: getattr(table, random_index)}
                )
            else:
                insert_unknown = sql.insert(table).values(**insert_values)

        return insert_unknown


@overload
def sql_command(
    calling_function: Callable[P, Coroutine[Any, Any, T]],
) -> Callable[P, Coroutine[Any, Any, T]]:
    """Decorator that wraps an async function with database session and transaction management.

    Using the decorator with no arguments will commit the results of running the function to the database and will assume that the name of the argument to the function that should contain the session is "session".
    """
    pass


@overload
def sql_command(
    commit_results: bool = True,
    session_keyword: str = "session",
) -> Callable[
    [Callable[P, Coroutine[Any, Any, T]]],
    Callable[P, Coroutine[Any, Any, T]],
]:
    """Decorator that wraps an async function with database session and transaction management.

    Parameters
    ----------
    commit_results : bool, optional
        Whether to commit the results of the session to the database, or roll them back in case of an error. Defaults to True.
    session_keyword : str, optional
        The name of the argument that is meant to store the session in the function. Defaults to "session".
    """
    pass


def sql_command(  # pyright: ignore[reportInconsistentOverload]
    commit_results: Callable[P, Coroutine[Any, Any, T]] | bool = True,
    session_keyword: str = "session",
) -> (
    Callable[
        [Callable[P, Coroutine[Any, Any, T]]],
        Callable[P, Coroutine[Any, Any, T]],
    ]
    | Callable[P, Coroutine[Any, Any, T]]
):
    if callable(commit_results):
        calling_function = commit_results
        commit_results = True
    else:
        calling_function = None

    def decorator(
        func: Callable[P, Coroutine[Any, Any, T]],
    ) -> Callable[P, Coroutine[Any, Any, T]]:
        @wraps(func)
        async def wrapper_func(*args, **kwargs) -> T:
            # Try to fetch the session if it already existed
            session_already_existed = isinstance(
                session := kwargs.get(session_keyword),
                SQLSession,
            )

            # It didn't exist, create a new one and add it to the kwargs
            if not session_already_existed:
                session = Session()
                kwargs[session_keyword] = session

            try:
                # Run the function and get the result
                if commit_results:
                    if not session.in_transaction():
                        async with session.begin():
                            result = await func(*args, **kwargs)
                        logger.debug(
                            "Database transaction committed successfully in %s.",
                            func.__qualname__,
                        )
                    else:
                        # If the session was already in a transaction, I begin a nested transaction
                        async with session.begin_nested():
                            result = await func(*args, **kwargs)
                else:
                    result = await func(*args, **kwargs)
            except BaseException as e:
                logger.error(
                    "An error occurred during database operation in %s: %s",
                    func.__qualname__,
                    e,
                )
                raise
            finally:
                # If the session was new, I close it here, but not otherwise
                if not session_already_existed:
                    await session.close()

            return result

        return wrapper_func

    if calling_function is not None:
        return decorator(calling_function)
    else:
        return decorator


# Create the async engine connecting to the database
logger.info("Creating engine to connect to database...")
engine = create_async_engine(
    f"{settings['db_dialect']}+{settings['db_driver']}://{settings['db_user']}:{settings['db_pwd']}@{settings['db_host']}:{settings['db_port']}/{settings['db_name']}",
    pool_pre_ping=True,
    pool_recycle=3600,
)
Session = async_sessionmaker(engine, class_=SQLSession, expire_on_commit=False)
logger.info("Created.")


def _compile_server_default(column: Column) -> str | None:
    """Return the server default value from a column as a raw SQL string.

    Parameters
    ----------
    column : :class:`~sqlalchemy.Column`
        The column to extract the server default from.

    Returns
    -------
    str | None
    """
    if column.server_default is None:
        return None
    arg = column.server_default.arg  # type: ignore
    return arg.text if hasattr(arg, "text") else str(arg)


def _quote(name: str, dialect: Dialect) -> str:
    """Quote an identifier (table or column name) for the given dialect.

    Parameters
    ----------
    name : str
        The identifier to quote.
    dialect : :class:`~sqlalchemy.Dialect`
        The SQLAlchemy dialect whose quoting rules to use (e.g. backticks for MySQL, double quotes for PostgreSQL).

    Returns
    -------
    str
    """
    return dialect.preparer(dialect).quote(name)


def _get_add_column_ddl(table_name: str, column: Column, dialect: Dialect) -> str:
    """Build an `ALTER TABLE ADD COLUMN` statement for adding a missing column to an existing table.

    Parameters
    ----------
    table_name : str
        The name of the table to alter.
    column : :class:`~sqlalchemy.Column`
        The ORM column definition to add.
    dialect : :class:`~sqlalchemy.Dialect`
        The SQLAlchemy dialect to use when compiling column types and quoting identifiers.

    Returns
    -------
    str
    """
    qt = _quote(table_name, dialect)
    qc = _quote(column.name, dialect)
    col_type = column.type.compile(dialect=dialect)
    nullable = "NULL" if column.nullable else "NOT NULL"
    default = ""
    server_default = _compile_server_default(column)
    if server_default is not None:
        default = f" DEFAULT {server_default}"
    return f"ALTER TABLE {qt} ADD COLUMN {qc} {col_type} {nullable}{default}"


def _get_modify_column_ddl(
    table_name: str,
    column: Column,
    dialect: Dialect,
    dialect_name: str,
) -> str:
    """Build an `ALTER TABLE MODIFY/ALTER COLUMN` statement for updating an existing column's type, nullability, or default.

    Parameters
    ----------
    table_name : str
        The name of the table to alter.
    column : :class:`~sqlalchemy.Column`
        The ORM column definition with the desired state.
    dialect : :class:`~sqlalchemy.Dialect`
        The SQLAlchemy dialect to use when compiling column types and quoting identifiers.
    dialect_name : str
        The name of the dialect (e.g. `"mysql"`, `"postgresql"`, `"sqlite"`).

    Returns
    -------
    str

    Raises
    ------
    NotImplementedError
        If the dialect is SQLite, which does not support `ALTER TABLE ALTER COLUMN`.
    """
    if dialect_name == "sqlite":
        raise NotImplementedError(
            f"SQLite does not support modifying columns. "
            f"Cannot modify {table_name}.{column.name}."
        )

    qt = _quote(table_name, dialect)
    qc = _quote(column.name, dialect)
    col_type = column.type.compile(dialect=dialect)
    nullable = "NULL" if column.nullable else "NOT NULL"
    default = ""
    server_default = _compile_server_default(column)
    if server_default is not None:
        default = f" DEFAULT {server_default}"

    if dialect_name == "mysql":
        return f"ALTER TABLE {qt} MODIFY COLUMN {qc} {col_type} {nullable}{default}"
    else:
        # PostgreSQL and others: must combine multiple ALTER COLUMN clauses
        parts = [
            f"ALTER COLUMN {qc} TYPE {col_type}",
            f"ALTER COLUMN {qc} {'DROP NOT NULL' if column.nullable else 'SET NOT NULL'}",
        ]
        if server_default is not None:
            parts.append(f"ALTER COLUMN {qc} SET DEFAULT {server_default}")
        else:
            parts.append(f"ALTER COLUMN {qc} DROP DEFAULT")
        return f"ALTER TABLE {qt} {', '.join(parts)}"


def _sync_columns(connection: Connection):
    """Inspect the database for each ORM table and synchronise the schema to match the ORM metadata.

    For each table that already exists in the database, this function will:

    - **Add** any columns present in the ORM metadata but missing from the database.
    - **Modify** any columns whose type, nullability, or server default differs between the ORM metadata and the database.

    Tables that do not yet exist are skipped — `create_all` is expected to handle those.

    Parameters
    ----------
    connection : :class:`~sqlalchemy.Connection`
        A synchronous SQLAlchemy connection (typically obtained via `run_sync`).

    Raises
    ------
    NotImplementedError
        If a column needs to be modified and the dialect is SQLite.
    """
    dialect_name = connection.dialect.name
    inspector = inspect(connection)
    for table_name, table in DBBase.metadata.tables.items():
        if not inspector.has_table(table_name):
            continue  # Table doesn't exist yet; create_all will handle it

        existing_columns = {
            col["name"]: col for col in inspector.get_columns(table_name)
        }
        for column in table.columns:
            if column.name not in existing_columns:
                ddl = _get_add_column_ddl(table_name, column, connection.dialect)
                logger.info("Adding missing column: %s.%s", table_name, column.name)
                connection.execute(text(ddl))
                continue

            # Skip primary key columns — modifying them risks losing AUTO_INCREMENT and other PK attributes
            if column.primary_key:
                continue

            # Check if the existing column needs modification
            existing = existing_columns[column.name]
            needs_modify = False

            # Compare nullability
            if existing.get("nullable") != column.nullable:
                needs_modify = True

            # Compare type (compile both to dialect-native strings and compare)
            expected_type = column.type.compile(dialect=connection.dialect)
            existing_type = existing["type"].compile(dialect=connection.dialect)
            if str(expected_type).upper() != str(existing_type).upper():
                needs_modify = True

            # Compare server default
            expected_default = _compile_server_default(column)
            existing_default = (
                str(existing["default"])
                if existing.get("default") is not None
                else None
            )
            if expected_default != existing_default:
                needs_modify = True

            if needs_modify:
                ddl = _get_modify_column_ddl(
                    table_name, column, connection.dialect, dialect_name
                )
                logger.info("Modifying column: %s.%s", table_name, column.name)
                connection.execute(text(ddl))

        # Sync unique constraints on individual columns
        existing_unique_columns: set[str] = set()
        for idx in inspector.get_indexes(table_name):
            col_names = idx.get("column_names", [])
            if idx.get("unique") and len(col_names) == 1 and col_names[0]:
                existing_unique_columns.add(col_names[0])

        for uc in inspector.get_unique_constraints(table_name):
            col_names = uc.get("column_names", [])
            if len(col_names) == 1 and col_names[0]:
                existing_unique_columns.add(col_names[0])

        for column in table.columns:
            if column.primary_key:
                continue

            if column.unique and column.name not in existing_unique_columns:
                logger.info(
                    "Adding missing unique constraint: %s.%s",
                    table_name,
                    column.name,
                )
                connection.execute(
                    text(f"ALTER TABLE {table_name} ADD UNIQUE ({column.name})")
                )


async def create_tables(target_engine: AsyncEngine | None = None):
    """Create all tables represented by the ORM classes, if they haven't already been created.
    Also adds any missing columns to existing tables.

    Parameters
    ----------
    target_engine : :class:`~sqlalchemy.ext.asyncio.AsyncEngine` | None, optional
        The engine to create/update tables on. Defaults to the module-level engine.
    """
    _engine = target_engine or engine
    logger.info("Ensuring all necessary tables exist...")
    try:
        async with _engine.begin() as conn:
            await conn.run_sync(DBBase.metadata.create_all)
            await conn.run_sync(_sync_columns)
    except Exception as e:
        logger.error("An error occurred while trying to create necessary tables: %s", e)
        raise
    logger.info("All necessary tables are available.")


@overload
async def register_observed_event(  # pyright: ignore[reportInconsistentOverload]
    channel_id: int,
    message_id: int | None = None,
    observed_at: datetime | None = None,
    *,
    session: SQLSession | None = None,
):
    pass


@sql_command
async def register_observed_event(
    channel_id: int,
    message_id: int | None = None,
    observed_at: "datetime | GenericFunction[datetime] | None" = None,
    *,
    session: SQLSession,
):
    """Register an event (such as a message send or bridge creation) in the `most_recent_event_in_channel` table.

    Parameters
    ----------
    channel_id : int
        The ID of the channel in which the event occurred.
    message_id : int | None, optional
        The ID of a message that triggered the event, if it was a message. Defaults to None.
    observed_at : :class:`~datetime.tatetime` | None, optional
        The UTC datetime when the event occurred. Defaults to None, in which case the current time will be used.
    session : :class:`~sqlalchemy.orm.Session` | None, optional
        An SQLAlchemy ORM Session connecting to the database. Defaults to None, in which case a new one will be created.
    """
    if observed_at is None:
        observed_at = func.now()
        now = datetime.now(timezone.utc)
    else:
        now = observed_at

    logger.debug(
        "Registering most recent event in channel <#%s> on %s.",
        channel_id,
        now,
    )

    upsert_new_event = await get_sql_upsert_query(
        DBMostRecentEventInChannel,
        indices={"channel"},
        channel=channel_id,
        message=message_id,
        observed_at=observed_at,
    )
    await session.execute(upsert_new_event)

    logger.debug("Event registered.")
